In [1]:
import geopy
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter

import pandas as pd

In [2]:
df = pd.read_csv("Data/NYPD_Complaint_Data_Current__Year_To_Date.csv")
df.head()

,CMPLNT_NUM,ADDR_PCT_CD,BORO_NM,CMPLNT_FR_DT,CMPLNT_FR_TM,CMPLNT_TO_DT,CMPLNT_TO_TM,CRM_ATPT_CPTD_CD,HADEVELOPT,HOUSING_PSA,...,TRANSIT_DISTRICT,VIC_AGE_GROUP,VIC_RACE,VIC_SEX,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,Lat_Lon,New Georeferenced Column
0,758521794,67,NaN,03/07/2021,01:50:00,NaN,NaN,COMPLETED,NaN,NaN,...,NaN,18-24,BLACK,M,1008789,177637,40.654223,-73.911563,"(40.654223423000076, -73.91156340899995)",POINT (-73.91156340899995 40.654223423000076)
1,696896951,60,NaN,03/26/2021,18:40:00,NaN,NaN,COMPLETED,NaN,NaN,...,NaN,25-44,BLACK HISPANIC,M,987641,148923,40.575443,-73.987795,"(40.57544276900006, -73.98779476299995)",POINT (-73.98779476299995 40.57544276900006)
2,972479923,75,BROOKLYN,03/27/2021,15:55:00,03/27/2021,16:00:00,COMPLETED,NaN,NaN,...,NaN,25-44,BLACK,F,1020990,186549,40.678643,-73.867543,"(40.67864264400004, -73.867542755)",POINT (-73.867542755 40.67864264400004)
3,109344500,77,BROOKLYN,03/28/2021,11:10:00,03/28/2021,11:23:00,COMPLETED,NaN,NaN,...,NaN,UNKNOWN,UNKNOWN,D,1004507,182865,40.668584,-73.926980,"(40.66858395700007, -73.92697993199994)",POINT (-73.92697993199994 40.66858395700007)
4,673945415,23,NaN,03/29/2021,23:13:00,NaN,NaN,COMPLETED,NaN,NaN,...,NaN,25-44,WHITE HISPANIC,M,1000267,228200,40.793026,-73.942156,"(40.793026087000044, -73.94215617799993)",POINT (-73.94215617799993 40.793026087000044)

In [4]:
df.shape

(204646, 36)

In [4]:
# creating a new dataframe with just lat and long 
df_latLong = df[['Latitude', "Longitude"]].copy()
df_latLong.head()

    Latitude  Longitude
0  40.654223 -73.911563
1  40.575443 -73.987795
2  40.678643 -73.867543
3  40.668584 -73.926980
4  40.793026 -73.942156

In [8]:
print (df_latLong.shape)

(204646, 2)

In [5]:
geolocator = geopy.Nominatim(user_agent="check_1")

In [28]:
def get_zip_code(x):
    location = geolocator.reverse("{}, {}".format(x["Latitude"],x["Longitude"]))
    return location.raw["address"]["postcode"]

In [20]:
print(df.iloc[0]["zipcode"])

11212

In [31]:
df_latLong["zipcode"] = df[0:100].apply(lambda x: get_zip_code(x), axis=1)

In [32]:
df_latLong.head()

    Latitude  Longitude zipcode
0  40.654223 -73.911563   11212
1  40.575443 -73.987795   11224
2  40.678643 -73.867543   11208
3  40.668584 -73.926980   11213
4  40.793026 -73.942156   10029

In [7]:
zip_input = input("Enter your zip code ")

Enter your zip code11105

In [8]:
print(zip_input)

11105

In [10]:
select_condition = df["zipcode"] == "11105"

In [11]:
df[select_condition]

,CMPLNT_NUM,ADDR_PCT_CD,BORO_NM,CMPLNT_FR_DT,CMPLNT_FR_TM,CMPLNT_TO_DT,CMPLNT_TO_TM,CRM_ATPT_CPTD_CD,HADEVELOPT,HOUSING_PSA,...,VIC_AGE_GROUP,VIC_RACE,VIC_SEX,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,Lat_Lon,New Georeferenced Column,zipcode
496,687423374,114,QUEENS,03/22/2021,06:00:00,03/22/2021,13:00:00,COMPLETED,NaN,NaN,...,25-44,WHITE,M,1009017,222644,40.777756,-73.910576,"(40.77775616400004, -73.91057612099996)",POINT (-73.91057612099996 40.77775616400004),11105
620,386273319,114,QUEENS,03/20/2021,04:00:00,03/20/2021,05:00:00,COMPLETED,NaN,NaN,...,45-64,WHITE,M,1012282,221437,40.774434,-73.898792,"(40.774433517000034, -73.89879234599994)",POINT (-73.89879234599994 40.774433517000034),11105
631,217149255,114,QUEENS,03/21/2021,18:00:00,03/25/2021,09:00:00,COMPLETED,NaN,NaN,...,45-64,ASIAN / PACIFIC ISLANDER,M,1009012,221484,40.774572,-73.910598,"(40.77457228400005, -73.91059844899996)",POINT (-73.91059844899996 40.77457228400005),11105
866,601300585,114,QUEENS,10/16/2020,17:30:00,03/25/2021,20:09:00,COMPLETED,NaN,NaN,...,UNKNOWN,UNKNOWN,D,1012381,221345,40.774181,-73.898435,"(40.77418068700007, -73.89843529299998)",POINT (-73.89843529299998 40.77418068700007),11105

In [12]:
df.columns

Index(['CMPLNT_NUM', 'ADDR_PCT_CD', 'BORO_NM', 'CMPLNT_FR_DT', 'CMPLNT_FR_TM',
       'CMPLNT_TO_DT', 'CMPLNT_TO_TM', 'CRM_ATPT_CPTD_CD', 'HADEVELOPT',
       'HOUSING_PSA', 'JURISDICTION_CODE', 'JURIS_DESC', 'KY_CD', 'LAW_CAT_CD',
       'LOC_OF_OCCUR_DESC', 'OFNS_DESC', 'PARKS_NM', 'PATROL_BORO', 'PD_CD',
       'PD_DESC', 'PREM_TYP_DESC', 'RPT_DT', 'STATION_NAME', 'SUSP_AGE_GROUP',
       'SUSP_RACE', 'SUSP_SEX', 'TRANSIT_DISTRICT', 'VIC_AGE_GROUP',
       'VIC_RACE', 'VIC_SEX', 'X_COORD_CD', 'Y_COORD_CD', 'Latitude',
       'Longitude', 'Lat_Lon', 'New Georeferenced Column', 'zipcode'],
      dtype='object')

In [ ]:
df_latLong[select_condition].zipcode.count()

In [60]:
select_condition = df["zipcode"] == "11105"
df_zip = df[select_condition]
df_zip.OFNS_DESC.value_counts().reset_index()
df_zip

,CMPLNT_NUM,ADDR_PCT_CD,BORO_NM,CMPLNT_FR_DT,CMPLNT_FR_TM,CMPLNT_TO_DT,CMPLNT_TO_TM,CRM_ATPT_CPTD_CD,HADEVELOPT,HOUSING_PSA,...,VIC_AGE_GROUP,VIC_RACE,VIC_SEX,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,Lat_Lon,New Georeferenced Column,zipcode
496,687423374,114,QUEENS,03/22/2021,06:00:00,03/22/2021,13:00:00,COMPLETED,NaN,NaN,...,25-44,WHITE,M,1009017,222644,40.777756,-73.910576,"(40.77775616400004, -73.91057612099996)",POINT (-73.91057612099996 40.77775616400004),11105
620,386273319,114,QUEENS,03/20/2021,04:00:00,03/20/2021,05:00:00,COMPLETED,NaN,NaN,...,45-64,WHITE,M,1012282,221437,40.774434,-73.898792,"(40.774433517000034, -73.89879234599994)",POINT (-73.89879234599994 40.774433517000034),11105
631,217149255,114,QUEENS,03/21/2021,18:00:00,03/25/2021,09:00:00,COMPLETED,NaN,NaN,...,45-64,ASIAN / PACIFIC ISLANDER,M,1009012,221484,40.774572,-73.910598,"(40.77457228400005, -73.91059844899996)",POINT (-73.91059844899996 40.77457228400005),11105
866,601300585,114,QUEENS,10/16/2020,17:30:00,03/25/2021,20:09:00,COMPLETED,NaN,NaN,...,UNKNOWN,UNKNOWN,D,1012381,221345,40.774181,-73.898435,"(40.77418068700007, -73.89843529299998)",POINT (-73.89843529299998 40.77418068700007),11105

In [38]:
df_latLong[0:100]

     Latitude  Longitude zipcode
0   40.853507 -73.882203   10460
1   40.696329 -73.937711   11206
2   40.805364 -73.937663   10035
3   40.892351 -73.856440   10466
4   40.887303 -73.845167   10466
..        ...        ...     ...
95  40.678916 -73.823446   11420
96  40.741133 -73.901088   11377
97  40.779380 -73.799027   11357
98  40.615352 -74.067065   10305
99  40.647832 -74.087015   10302

[100 rows x 3 columns]

In [ ]:
# so far the data only has zipcodes for 100 rows, need to run function to make sure the zipcodes gets to all the lat and longs

### Zip Code Funtion 2.0

In [ ]:
geocoder = Nominatim(user_agent = 'check_1')
geocode = RateLimiter(geocoder.geocode, min_delay_seconds = 1,   return_value_on_exception = None)

In [ ]:
def get_zip_code2(x):
    location = geocode.reverse("{},{}".format(x["Latitude"], x["Longitude"]))
    #location = geocode.reverse("{}, {}".format(x["Latitude"],x["Longitude"]))
    return location.raw["address"]["postcode"]

In [19]:
def get_zipcode3(df, geolocator, Latitude, Longitude):
    location = geolocator.reverse((df[Latitude], df[Longitude]))
    return location.raw['address']['postcode']


#geolocator = geopy.Nominatim(user_agent='check_1')

In [ ]:
df["zipcode"] = df[0:1000].apply(lambda x: get_zip_code2(x), axis=1)

In [22]:
df["zipcode"] = df.apply(get_zipcode, axis=1, geolocator=geolocator, Latitude='Latitude', Longitude='Longitude')

GeocoderUnavailable: ("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /reverse?lat=40.71407409000005&lon=-73.94937419199994&format=json&addressdetails=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x11a453860>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))", 'occurred at index 467')